### ISSUE TITLE
`nxp3 contract invoke ...` error message is not helpful when specifying invalid arguments

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-express#94] opened 2020-12-19 05:01 UTC
This invoke file (note the empty string as the 4th argument):
```
[
  {
    "contract": "GasToken",
    "operation": "transfer",
    "args": [
      "@genesis",
      "@registrant1",
      10000000,
      ""
    ]
  }
]
```
causes this output:
`Index was outside the bounds of the array. [IndexOutOfRangeException]`

**Comment by devhawk** [comment] 2021-05-05 00:24
dupe of #136

**Closed by devhawk** 2021-05-05 00:24 UTC
Labels: duplicate
