### ISSUE TITLE
contract download chain replication

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-express#226] opened 2022-04-07 07:36 UTC
see point `2.` of https://github.com/neo-project/neo-express/pull/209#discussion_r839545295

**Comment by devhawk** [comment] 2022-04-21 23:27
@ixje Isn't this a duplicate of #225 ?

**Comment by ixje** [comment] 2022-04-22 07:15
Not necessarily. There is a lot of overlap for OnlineNode's but not for offline or batch ones. The difference might be small enough to merge the 2 issues though. If we keep them separate then this issue should be resolved before #225 .

**Comment by devhawk** [comment] 2022-08-15 18:45
I'm going to close this issue as a dupe of #255.

**Closed by devhawk** 2022-08-15 18:45 UTC
Labels: duplicate

**Comment by ixje** [comment] 2022-08-15 18:57
This is not a duplicate though. 
iirc #225 is about downloading from a source network into a multi-node private network, whereas this issue is about how a client connected to the private network that had a contract downloaded on its chain will get the new state information because there is no deploy transaction. Solving this issue could however automatically solve #225 

Either way, I think this issue has more context than #225 and should therefore take precedence over #225. just my 2 cents
