### ISSUE TITLE
Error running "neoxp contract download" command: System.InvalidCastException

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#277] opened 2023-04-11 23:16 UTC
Hi,

I am currently encountering an error while running the following command:
 `neoxp contract download 0x4380f2c1de98bb267d3ea821897ec571a04fe3e0 MainNet`

Error message: `System.InvalidCastException: Unable to cast object of type 'Neo.Json.JString' to type 'Neo.Json.JObject'.`

If I don't include the network name, I get another error:
```
neoxp contract download 0x4380f2c1de98bb267d3ea821897ec571a04fe3e0
System.ArgumentException: Invalid RpcUri value ""
```

**Comment by ixje** [comment] 2023-04-12 07:04
Duplicate of https://github.com/neo-project/neo-express/issues/262

Upgrade your neoxp. I believe there is no regular release yet, so you'll have to use this to install a preview version
```
> dotnet tool update Neo.Express -g --add-source https://pkgs.dev.azure.com/ngdenterprise/Build/_packaging/public/nuget/v3/index.json
```

**Closed** 2023-04-12 18:15 UTC
